//! [Generates] trait for data accumulation during graph traversal.
//!
//! Where [crate::Composable] is 1:1 this is 1:many

use crate::error::Error;
/// [`Generates`] is a trait that allows `Self` to generate instances of
/// type `Target` with type `With`.
///
/// This is used in an Areamy graph for nodes to yield information based
/// on existing signals.
///
/// A [`Generates`] operation only references [self] type so that
/// it can be repeatedly applied from an anchor.
///
/// Each message type can be composed with
/// many other but each pair can only produce one. That
/// is why we are generic over `With` but `To` is an
/// associated type.
pub trait Generates<With> {
    /// [Generates::Target] is the unique type generated by Self with With
    type Target;
    // Generate an instance of `Self::Target` with `With`.
    fn generate(&self, argument: With) -> Result<Self::Target, Error>;

    // Generation can start without having seen a [self] instance so all
    // `Generates` types must support a With-only case. [Generates::start]
    // is not necessarily only invoked once. There may be a long prefix
    // of generation without context all produced with `start`.
    fn start(argument: With) -> Result<Self::Target, Error>;
}
